version: '3.8'

services:

  web:
    container_name: 'webapi'
    image: 'webapi'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__SQLConnectionString=Host=postgres;Port=5432;Database=promocodefactorydb;Username=postgres;Password=password;
    depends_on:
     - "postgres"

  postgres:
    image: postgres:latest
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
      
volumes:
  pg-data:

networks:
  default:
    name: myLocalNetwork # создана извне: docker network create --driver=bridge myLocalNetwork
    external: true    